version: "3"

networks:
  comms:
    external: false

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    networks: [comms]
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/influxdb.config:/etc/influxdb/influxdb.conf:ro
      - ./influxdb/init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/influxdb
      - db-backup:/backup
    environment:
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
    networks: [comms]
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log

  node-red:
    build:
      context: ./node-red
    container_name: node-red
    restart: always
    networks: [comms]
    volumes:
      - node-red-data:/data
    environment:
      - TZ=${TIMEZONE}

volumes:
  db-data: {}
  db-backup: {}
  mosquitto-data: {}
  mosquitto-log: {}
  node-red-data: {}
