version: "3"

networks:
  comms:
    external: false

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    networks: [comms]
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/influxdb.config:/etc/influxdb/influxdb.conf:ro
      - ./influxdb/init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/influxdb
      - db-backup:/backup
    environment:
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    networks: [comms]
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log

  node-red:
    build:
      context: ./node-red
    container_name: node-red
    restart: always
    networks: [comms]
    volumes:
      - node-red-data:/data
    environment:
      - TZ=${TIMEZONE}

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '8053:80/tcp'
    volumes:
      - ${PIHOLE_BASE}/etc-pihole:/etc/pihole
      - ${PIHOLE_BASE}/etc-dnsmasq.d:/etc/dnsmasq.d
    environment:
      - VIRTUAL_HOST="pi.hole"
      - VIRTUAL_PORT="80"
      - PROXY_LOCATION="pi.hole"
      - FTLCONF_LOCAL_IPV4="192.168.71.190"
      - WEBPASSWORD=${PIHOLE_PASSWORD}
      - TZ=${TIMEZONE}
    restart: unless-stopped

  ntp:
    image: cturra/ntp:latest
    container_name: ntp
    ports:
      - '123:123/udp'
    restart: always
    environment:
      - NTP_SERVERS=0.pl.pool.ntp.org,1.pl.pool.ntp.org,2.pl.pool.ntp.org,3.pl.pool.ntp.org
      - LOG_LEVEL=0
      - TZ=${TIMEZONE}

volumes:
  db-data: {}
  db-backup: {}
  mosquitto-data: {}
  mosquitto-log: {}
  node-red-data: {}
