version: "3"

networks:
  smart-home_comms:
    external: true

services:
  grafana:
    build: 
      context: ./grafana
    container_name: grafana
    restart: always
    networks: [smart-home_comms]
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
    environment:
      - GF_STRAVA_DS_DATA_PATH=/var/lib/grafana/strava

  www:
    build:
      context: ./www
      dockerfile: Server/Dockerfile
    container_name: www
    restart: always
    networks: [smart-home_comms]
    volumes:
      - ${FIRMWARE_DIRECTORY}:/firmwares/
      - www-data:/data
    environment:
      - TZ=${TIMEZONE}

  nginx:
    image: "nginx"
    container_name: nginx
    restart: always
    networks: [smart-home_comms]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/certs:ro
    ports:
      - "443:443"
    depends_on:
      - grafana
      - www

volumes:
  grafana-data: {}
  www-data: {}
