FROM grafana/grafana:10.2.0

USER root
COPY data /var/lib/grafana
RUN chown -R grafana /var/lib/grafana
RUN chmod 777 /tmp/

USER grafana
RUN grafana-cli plugins install grafana-strava-datasource

VOLUME /var/lib/grafana
